{% set version = '0.2-22' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modeltools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modeltools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modeltools/modeltools_{{ version }}.tar.gz
  sha256: 256a088fc80b0d9182f984f9bd3d6207fb7c1e743f72e2ecb480e6c1d4ac34e9

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('modeltools')"           # [not win]
    - "\"%R%\" -e \"library('modeltools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=modeltools
  license: GPL-2
  summary: A collection of tools to deal with statistical models.  The functionality is experimental
    and the user interface is likely to change in the future. The documentation is rather
    terse, but packages `coin' and `party' have some working examples. However, if you
    find the implemented ideas interesting we would be very interested in a discussion
    of this proposal. Contributions are more than welcome!
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: modeltools
# Title: Tools and Classes for Statistical Models
# Date: 2018-07-16
# Version: 0.2-22
# Author: Torsten Hothorn, Friedrich Leisch, Achim Zeileis
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Description: A collection of tools to deal with statistical models.  The functionality is experimental and the user interface is likely to change in the future. The documentation is rather terse, but packages `coin' and `party' have some working examples. However, if you find the implemented ideas interesting we would be very interested in a discussion of this proposal. Contributions are more than welcome!
# Depends: stats, stats4
# Imports: methods
# LazyLoad: yes
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2018-07-16 13:56:35 UTC; hothorn
# Repository: CRAN
# Date/Publication: 2018-07-16 16:44:58 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
