travis:
  secure:
    BINSTAR_TOKEN: z/5uCgVQ2PTei6zj08uTB30ZAIMe6NoM8Z1XgXvbtUqCfXjI0NvC5Vm15qwQ/IavV5r7eZ0NPMS+U/I+MS8ZhSMb0pzvpyJipgS16u5U7twuE0H3sbePEFokxe6Nm0jVtefx69sy8IMHZRVaXu4zR+sUBqNfyBBz9oyXhaQbNmGL1jSg8HFpwT81tNW19sjIJJT+IM0EYMol+V23LL21ouyVEV17v0J7fXkeKoiQ3utH/pfTY3PqojGBWj+P+u02AtlWiYsUdTZy5IcUWHbg8DSQAiLHlUStPL9cycdGb6bv+/ugpiNjXQoMSvKLOpFMem3iVcFcAk+6s1qD0Z+FK6CxyN0o75ky0GgrLep5zRDUe4Fyc1HldMuvuN2icmJWSnwsw/NZCXRA+jUpZ9+NQobbiQ8e5VunUaiG22Ou7MRrQ8a8Hp1SPm0PU8XLKfRHduxbOw+GdDWBsdNphfc5NeQzJ9RKX5JHhQt4ti3gZ9Qpq8cPCVGwzKPjbMl0ACMlqGfkduv7CwLbooZbMqjnycoQWxn515R84ONiG1olJfoPJLfXbU2t5R92UBI1JH9VsFcQ96/GlfYvsHUQvPeK9auq60YwjDqtzGIIHLNJsdCDLFLw6nDJeLsyQjd4bPKFK3q2UxdCWCh5gztssgRZxOClcZ2rJ/xLxtRVZYtBGzo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
