travis:
  secure:
    BINSTAR_TOKEN: u7MFvzpyy9GFIjPqUGhq4+7ON/LRlZDLEBvUEVZtAqLKST9SPwceSOMY7sZ91nlJQe6E/+KnhGjwU0qcQRNDkgepNwqp4qShg088cKkYXQnwGdQY9HXHU4c+/fVMv/u7RKvwi7XbDW6fJ6SpHO9Xmcr8FSQKuve1iQB2/qbvbSUUD46T+/ev9SvDCxNptH8/ge6toAlqlfizUuDFMLl3IwNY3eYp2j9/P4n22eifnSnI4pDuzoOPZhwiacdCH3b9SGlBSR1U71HkggKVluGlwAObaib5SGnu/4DPkd1qo/kFyYIAfJ4MMVlAqBo4yNoOTXoUaMwc4wbKd1PsIaodAa1h0bm1C6yJvZ/ljk3Pj9gIRO+pA78QgBRANcAha8yNm0NP/v4IjswaNMIn47oqC4rzPil4M4nohtUpWQo+vRKrglbLXDloGl1fDT1KIdp1tEPf7/ClHVDCHDUZYpqMtYnqJuMnO12Jx98VTt2DF22IvawkHdF6vG7oG4tAliFW05RsYfUkdPefaStomTqjodrNzQi+W4eQ1F1vgxNrcByxBkjT41aHTBenCAf+TDh25Aew3antjt9evug7D2rbrPpT2DtzYjmUWuq22NNBYs2JOyBSRTCXK5cwpwlX5oEJcUa9fOtkz0uPGPCUoMtTUtDoCR3HOL8V2oTNfCxD8Z8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
